ci:
  autofix_prs: true
  autoupdate_schedule: weekly
  autoupdate_commit_msg: 'chore: pre-commit autoupdate'

repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v6.0.0
  hooks:
  - id: check-json
    exclude: ^.vscode/launch\.json$
  - id: check-toml
  - id: check-yaml
  - id: end-of-file-fixer
  - id: trailing-whitespace

- repo: https://github.com/charliermarsh/ruff-pre-commit
  rev: v0.12.9
  hooks:
  - id: ruff-check
    args: [--fix, --exit-non-zero-on-fix]
  - id: ruff-format
