[build-system]
build-backend = "hatchling.build"
requires = [ "hatch-vcs==0.5", "hatchling==1.30.1" ]

[project]
name = "meltano-tap-hubspot"
description = "Singer tap for Hubspot, built with the Meltano Singer SDK."
readme = "README.md"
keywords = [
  "ELT",
  "tap-hubspot",
]
license = "Apache-2.0"
requires-python = ">=3.10"
classifiers = [
  "Programming Language :: Python :: 3 :: Only",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: 3.13",
  "Programming Language :: Python :: 3.14",
]
dynamic = [ "version" ]
dependencies = [
  "backports-datetime-fromisoformat==2.0.3; python_full_version<'3.11'",
  "requests==2.34.2",
  "singer-sdk~=0.54.4",
  "typing-extensions>=4.15.0 ; python_full_version < '3.12'",
]
[[project.authors]]
name = "Ethan Stein"
[project.optional-dependencies]
s3 = [ "s3fs>=2025.7" ]
[project.scripts]
tap-hubspot = "tap_hubspot.tap:TapHubspot.cli"

[dependency-groups]
dev = [
  "pytest>=9",
  "singer-sdk[testing]",
]

[tool.hatch.build.targets.sdist]
include = [ "tap_hubspot" ]
[tool.hatch.build.targets.wheel]
include = [ "tap_hubspot" ]
[tool.hatch.version]
fallback-version = "0.0.0.dev0"
source = "vcs"

[tool.uv]
default-groups = "all"
required-version = ">=0.12"

[tool.ruff]
required-version = ">=0.16"
src = [ "tap_hubspot" ]
[tool.ruff.lint]
ignore = ["CPY"]
select = [ "ALL" ]
[tool.ruff.lint.flake8-annotations]
allow-star-arg-any = true
[tool.ruff.lint.isort]
known-first-party = [ "tap_hubspot" ]
[tool.ruff.lint.pydocstyle]
convention = "google"

[tool.mypy]
follow_untyped_imports = true
warn_redundant_casts = true
warn_unused_ignores = true
warn_unused_configs = true
