# This file can be used to customize tox tests as well as other test frameworks like flake8 and mypy

[tox]
envlist =
    3.{10-}
    format
    lint
isolated_build = true
requires =
     tox>=4.55
     tox-uv>=1.35

[testenv]
description = run tests on Python {py_dot_ver}
deps =
    pytest
commands =
    pytest

[testenv:format]
description = format
skip_install = true
deps =
    ruff
commands =
    ruff check tap_hubspot/
    ruff format tap_hubspot/

[testenv:lint]
description = lint
base_python_file = .python-version
deps =
    mypy
    ruff
    types-requests
commands =
    ruff check --diff tap_hubspot/
    ruff format --check tap_hubspot/
    mypy .
